# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools 
        pip-sync app/requirements.txt app/dev-requirements.txt
        sudo apt-get install -y build-essential dcmtk inetutils-ping libqt5core5a redis
        pip install flake8 pytest pytest-asyncio 
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefinedp names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --statistics
    - name: typecheck with mypy
      run: |
        mypy --exclude app/tests --no-namespace-packages . 
    - name: Test with pytest
      if: always()
      run: |
        python -m pytest -vvv
    - name: Check getdcmtags version
      run: |
        cd getdcmtags && ./check_version.sh
